### ISSUE TITLE
Validation fails after submit of incomplete/invalid form's data

### ISSUE THREAD

**Issue by maxmishyn** [derhansen/form_crshield#21]
Steps to reproduce:
1. Make a for with just 1 single mandatory field.
2. Submit that form with empty required field
3. You'll land on form with validation errors. Complete requires field and submit.
4. CR validation will fails and none of form's finishers will be executed

From what I can see the reason is following:
1. When form is generated for a first time it generates challene AAA with timestamp 1000.
2. JS transforms it into 1000|BBB
3. On invalid form submit form hook validates str_rot13('BBB')==='AAA' as valid. Anf in the same time generates the new challenge: 2000|CCC
4. Next I'm not sure, but most probably Form applies POST data to the cr-field and fenerates form with required field validation errors. It measn that form sends to client "1000|BBB" as a challenge anstead of new "2000|CCC" 
5.  JS on the client side transforms "1000|BBB" into "1000|AAA"
6. When client submits data CR from handler retrieves challenge for timestamp 1000 from the request which is "AAA" and fails validation with str_rot13('AAA')!=='AAA'

**Comment by derhansen** [comment]
Thanks for your report.

When the form is submitted with a valid CR value but server side validation fails, the form is shown with the validation message but with the POSTed (and validated) CR value. The JavaScript then however performs the ROT13 calculation on the CR field again, resulting in the described problem. 

This scenario can be catched in JavaScript, because a POSTed CR value does not contain any `delay`, which therefore is evaluated to `undefined`. I

**Comment by derhansen** [comment]
@maxmishyn I created a fix for the issue and added acceptance tests to cover the scenario. Would you mind to test the fix, which has been pushed to the development branch?

**Comment by derhansen** [comment]
Fix will be included in the upcoming version 1.4.0
