### ISSUE TITLE
Form does not get sent with version 1.4.0

### ISSUE THREAD

**Issue by oliverklee** [derhansen/form_crshield#27]
The affected installation is using TYPO3 10.4.37 with PHP 7.4 and `helhum/typo3-secure-web` 0.3.2.

We have an contact email form there that is using EXT:form and this extension.

With version 1.3.2, I can submit the form (and get the email sent) without problems, and I see the thank-you page of the form.

With version 1.4.0, after submitting, the form gets displayed again (with the data I entered), no email is sent, and this gets logged in the TYPO3 debug log:

```
Thu, 01 Feb 2024 13:08:54 +0100 [DEBUG] request="19c4ec7b1b692" component="Derhansen.FormCrshield.Hooks.Form": Submitted data - {"text-1":"Oliver Klee","DZ7Fyhu1ivOeLGbaW3nXrmq":"","text-2":"redacted@example.com","text-3":"+49 +49 123 45678","textarea-1":"Test","cr-field":"MHwyOHA4cjNuMDc0czhxcXMwODU4bnFxNTQ3bzlycDM4M3M1cDk4MG4z"}
Thu, 01 Feb 2024 13:08:54 +0100 [DEBUG] request="19c4ec7b1b692" component="Derhansen.FormCrshield.Hooks.Form": CR response expired. Submitted data - {"text-1":"Oliver Klee","DZ7Fyhu1ivOeLGbaW3nXrmq":"","text-2":"redacted@example.com","text-3":"+49 +49 123 45678","textarea-1":"Test","cr-field":"MHwyOHA4cjNuMDc0czhxcXMwODU4bnFxNTQ3bzlycDM4M3M1cDk4MG4z"}
Thu, 01 Feb 2024 13:08:54 +0100 [DEBUG] request="19c4ec7b1b692" component="Derhansen.FormCrshield.Hooks.Form": CR response expired. Submitted data - {"text-1":"Oliver Klee","DZ7Fyhu1ivOeLGbaW3nXrmq":"","text-2":"redacted@example.com","text-3":"+49 123 45678","textarea-1":"Test","cr-field":"MHwyOHA4cjNuMDc0czhxcXMwODU4bnFxNTQ3bzlycDM4M3M1cDk4MG4z"}
```

(What stands out to me there is the "CR response expired" message.)

I've checked that `FormCrShield.js` gets loaded when I load the page and that there are no errors or warnings in the browser console.

Is this a bug, or has version 1.4.0 some breaking change that requires changes to the extension configuration?

And how can I help debug this?

**Comment by derhansen** [comment]
Thanks for your report. I could reproduce the problem with TYPO3 10.4. There was a change regarding the results of the `getTsfe()` function, which set the default page lifetime to `0`, if `TSFE` could not be resolved. (see https://github.com/derhansen/form_crshield/pull/23/files#diff-ce917b920dec5a667900b0457599cede7853ff5f3cebb7c8c45bf77c9e9aa599R110)

This is actually ok, but revealed, that the `getTsfe()` function never worked correctly for TYPO3 v10, since the PSR-7 request attribute `frontend.controller` was introduced in TYPO3 v11 and the function thereby always returned `null` and the page lifetime defaulted to 86400 seconds. 

I fixed the problem by using `$GLOBALS['TSFE']` for TYPO3 v10 and published version 1.4.1 on TER and packagist.
