### ISSUE TITLE
[BUG] Summary step does not validate

### ISSUE THREAD

**Issue by helsner** [derhansen/form_crshield#8]
Hi, nice extension!
it works perfectly fine for normal or multistep forms.
Also good to test with disabled javascript.

I got an issue with summary steps though, which seem not to validate.
The `$requestArguments` are empty in my case so the validation fails in the afterSubmit function with the `CR response invalid. Submitted data` logs

`EXT:form_crshield/Classes/Hooks/Form.php:72`

**Comment by derhansen** [comment]
The issue has been fixed in develop branch. Also, I have added acceptance tests for the extension to ensure, that different scenarios work as expected with a webbrowser (chrome headless with JavaScript) and phpbrowser (simulates a bot with no JavaScript support). See https://github.com/derhansen/form_crshield/actions/runs/3354937056/jobs/5558827833
